# Generated by Django 2.2.7 on 2020-04-15 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROName', models.CharField(max_length=50, verbose_name='اسم المنتج :')),
                ('PRODesc', models.TextField(verbose_name='الوصف : ')),
                ('PROImage', models.ImageField(upload_to='productImg', verbose_name='Image ')),
                ('PROCreated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create At ')),
                ('PROSlug', models.SlugField(blank=True, null=True, verbose_name='Product Slug')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
